.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH shake 1  "shake " 
.SH NAME
shake
.SH SYNOPSIS
\fBshake\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
shake\-init(1)
Create a new project in the current directory
.TP
shake\-new(1)
Create a new project in a directory with the given name
.TP
shake\-clone(1)
Create a project structure with the project at the given uri
.TP
shake\-help(1)
Print this message or the help of the given subcommand(s)
